PR Test
Solo83/TennisScoreboard pull request #1
Opened 2024-05-02 10:36 UTC by Solo83

PR Test

2024-05-02 21:01 UTC, Badbadr requested changes
Часто

2024-05-02 21:01 UTC, Badbadr commented on src/test/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Использование wildcard в импортах нежелательно, привыкай испортить только то, что используешь

2024-05-03 07:35 UTC, Solo83 commented
Исправил.

2024-05-03 08:24 UTC, Badbadr requested changes

2024-05-03 08:24 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/Runner.java
>  import org.hibernate.*;
Тут тоже импортишь сразу все. Погугли как в идее отключить автозамену импорта нескольких методов из либы на wildcard

2024-05-03 08:24 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
> +                transaction.rollback();
В этом моменте подключение уже закрыто, вроде как не имеет смысла откатывать транзакцию. Поизучай этот вопрос детальнее

2024-05-03 08:24 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/Runner.java
>  import org.hibernate.*;
Сори, не тут, на 7 строчке

2024-05-03 08:24 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
> +            addedPlayer = Optional.of(session.get(Player.class, player.getId()));
Вместо одного запроса на получение игрока используется два, посмотри как получить id игрока при его инсерте, чтобы не нужно было после его добавления сразу селектить его же

2024-05-03 08:33 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/Runner.java
>  import org.hibernate.*;
Исправил. Раннер класс использовался для тестирования. Сейчас добавил логирование.

2024-05-03 08:50 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
> +            addedPlayer = Optional.of(session.get(Player.class, player.getId()));
session.persist(player); после этого метода у переданного объекта сетится Id. Поэтому можно вернуть текущий player, он будет моделью из таблицы.

2024-05-03 09:18 UTC, merged