New players saving to repository
Solo83/TennisScoreboard pull request #3
Opened 2024-05-07 10:20 UTC by Solo83

Added exception handling classes:

RepositoryException.java
ValidatorException.java

The error is recorded in the request attribute and is subsequently displayed to the user on the new_match.jsp page. If there is no error, users are recorded in the database.

Added classes:
ParameterValidator.java - contains the logic for validating the parameter from the request.
Expressions.java - Contains static RegExp templates for text strings.

Added dependencies for testing:
mockito-core
mockito-junit-jupiter

Added tests for ParameterValidator:
PlayerName_WithTwoWords_ShouldPassValidation
PlayerName_WithOneWord_ShouldThrowException

2024-05-08 15:30 UTC, Badbadr requested changes

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
>  import java.io.*;
Убрать *

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
>  import jakarta.servlet.http.*;
Убрать *

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
>  import jakarta.servlet.annotation.*;
Убрать *

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +        } catch (ValidatorException | RepositoryException e) {
А если возникнет другая ошибка?

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +    PlayerRepositoryImpl playerRepository = new PlayerRepositoryImpl();
Тут создается объект репозитория. Конкретно сейчас все ок, он создается в только в одном месте. Но может быть хуже. Почитай про паттерны singltone и prototype. Подумай, как можно подключить репозиторий иначе

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            String firstPlayerName = req.getParameter("player1name");
А если в запросе нет таких полей?

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            Player player1 = new Player(firstPlayerName);
Зачем отдельно создавать игрока и затем передавать его на сохранение? Почему бы отдать эту логику сервису?

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            Optional<Player> player1Optional = playerRepository.addPlayer(player1);
Обычно, репозитории напрямую не используются в контроллерах. Как правило есть слой бизнес логики (сервисы) к которым обращаются контроллеры, а сами сервисы используют репозитории. Почитай про mvc, попробуй найти примеры проектов (не других реализаций roadmap'a) а вообще любого проекта на том же гите

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepository.java
> +    Optional<Player> getPlayer(String playerName) throws RepositoryException;
обычно методы получения содержат в названии поле, по которому происходит поиск, в данном случае getPlayerByName

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>              Session session = HibernateUtil.getSessionFactory().openSession();
Небезопасная работа с сессией, почитай про try-with-resource

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>                  transaction.rollback();
Тут происходит обычный селект. Если оборачивание его в транзакцию еще могу понять, то что ожидается при откате транзакции с селектом?

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>                  transaction.rollback();
Аналогично

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>              Session session = HibernateUtil.getSessionFactory().openSession();
Аналогично

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>              Session session = HibernateUtil.getSessionFactory().openSession();
Аналогично

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/ParameterValidator.java
> +        Pattern pattern = Pattern.compile(expression);
Компилируешь регулярку каждый раз при вызове метода, зачем?

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/Expressions.java
> +public class Expressions {
Держать отдельный класс для регулярки (даже большого кол-ва) как будто не нужно. Можешь регулярки держать в классах валидации

2024-05-08 15:30 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/Expressions.java
> +    public static final String PLAYER_PATTERN = "(\\w+\\s+\\w+)";
Разрешаешь в именах цифры и _?

2024-05-10 12:42 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +    PlayerRepositoryImpl playerRepository = new PlayerRepositoryImpl();
Сделал класс Репозиторя синглтоном

2024-05-10 13:02 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            String firstPlayerName = req.getParameter("player1name");
Валидатор кинет исключение

2024-05-10 13:07 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            Optional<Player> player1Optional = playerRepository.addPlayer(player1);
Добавил PlayerService

2024-05-10 13:08 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepository.java
> +    Optional<Player> getPlayer(String playerName) throws RepositoryException;
Переименовал метод

2024-05-10 13:08 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>              Session session = HibernateUtil.getSessionFactory().openSession();
Обернул

2024-05-10 13:08 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>                  transaction.rollback();
Откат не имеет смысла. Убрал.

2024-05-10 13:12 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/Expressions.java
> +public class Expressions {
Перенесу в класс валидации. Текущий класс удалю.

2024-05-10 13:47 UTC, Solo83 commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/Expressions.java
> +    public static final String PLAYER_PATTERN = "(\\w+\\s+\\w+)";
Переписал выражение

2024-05-11 09:52 UTC, Badbadr requested changes

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/controller/NewMatch.java
> +            playerService.savePlayer(new Player(firstPlayerName));
Так делать не стоит. Как правило сервис - это бизнес логика. Тут ты называешь метод savePlayer и передаешь ему на вход инстанс Player. Хоть это и выглядит логично и работать это будет правильно, есть пара проблем:
1) Сохранять должен не сервис, а репозиторий. Сервис должен создавать, то есть осуществлять "бизнес" логику, в репозиторий должен персистить данные в бд. Тут важно разделение обязанностей
2) Так как создавать должен сервис, странным выглядит создание инстанса Player для передачи его в метод создания
3) Так как создает обычно сервис, в метод создания лучше всего передавать не инстанс и не поля необходимые для создания инстанса по отдельности. Лучше создавать отдельный dto (Data Transfer Object) класс, который будет содержать необходимые для создания сущности поля и его передавать от контроллера в сервис (хотя тут только одно поле и в целом наверное ок, но лучше попробуй сделать через dto чтобы в дальнейшем было понимание)

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
>              if (transaction != null) {
Так как ты добавил try-with-recource на данном этапе (могу ошибаться, перепроверь) сессия уже закрыта и транзакции нет. Посмотри как лучше откатывать транзакции в случае ошибок

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/service/PlayerService.java
> +public class PlayerService {
Хорошей практикой является создание сервисов как имплементаций интерфейса PlayerService (по аналогии с репозиторием)

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/service/PlayerService.java
> +    public void savePlayer(Player player) throws RepositoryException {
Лучше будет просто create()

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/PlayerNameValidator.java
> +        if (!parameterMap.containsKey(parameterName)) {
1)

2024-05-11 09:52 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/utils/validator/PlayerNameValidator.java
> +            String parameterValue = parameterMap.get(parameterName)[0];
Ты обращаешься к мапке тут второй раз (перед этим стоит метка 1.). В целом метод вызывается довольно часто и не хочется делать опреацию по получению два раза. Можно обойтись одним. Подумай как

2024-05-13 14:49 UTC, Badbadr requested changes

2024-05-13 14:49 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/service/PlayerService.java
> +    void create(PlayerDTO playerDTO) throws RepositoryException;
Чаще всего видел, что методы создания возвращают созданный инстанс

2024-05-13 14:49 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/dto/PlayerDTO.java
> +public class PlayerDTO {
Хорошей практикой является говорящее название классов. Для чего он используется? Для передачи данных в запросе - GetPlayerRequest. Для передачи данных в ответе - GetPlayerResponse. Тут эти сущности никак не отличаются и отличий вроде не появится при развитии проекта, поэтому можно оставить и один класс. Но для тренировки, можешь наплодить разных классов под запросы-ответы

2024-05-13 14:49 UTC, Badbadr commented on src/main/java/com/solo83/tennisscoreboard/repository/PlayerRepositoryImpl.java
> +    public Optional<Player> addPlayer(Player player) throws RepositoryException {
Работаем с бд, save будет достаточно

2024-05-17 10:59 UTC, merged